### ISSUE TITLE
K-Lapse 5.0 missing

### ISSUE THREAD

**Issue by alibei** [tanish2k09/KLapse-Livedisplay#4]
Hello,

K-Lapse is not working with latest build. Any kernel manager wont show the K-Lapse settings. Even the files are missing in /dev/module/klaspe

**Comment by tanish2k09** [comment]
Can you drop a link to the commits to your kernel source code along with any info you might think is helpful for me?

**Comment by alibei** [comment]
Oh sorry it is working now my fault

**Comment by TwistedPrime** [comment]
@alibei

**Comment by Panchajanya1999** [comment]
@alibei hi sar klapse nu warks
